@extends('pdf.layout')

@section('title', 'Beneficiaries by Program Report')

@section('header_id')
    Invoice ID: {{ $invoice->invoice_number }}
@endsection

@section('content')
    <table class="products">
        <thead>
            <tr>
                <th>Program</th>
                <th>Total Beneficiaries</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($beneficiaries as $beneficiary)
                <tr>
                    <td>{{ $beneficiary['program'] }}</td>
                    <td>{{ number_format($beneficiary['total']) }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="2" style="text-align: center;">No data available for this period.</td>
                </tr>
            @endforelse
        </tbody>
        <tfoot>
            <tr style="font-weight: bold; border-top: 2px solid #000;">
                <td>Total</td>
                <td>{{ number_format($beneficiaries->sum('total')) }}</td>
            </tr>
        </tfoot>
    </table>

    <div class="total">
        Grand Total: {{ number_format($beneficiaries->sum('total')) }}
    </div>
@endsection

@section('header_extra')
    <div>Report Date: {{ now()->format('Y-m-d') }}</div>
    <div>Generated by: {{ auth()->user()->name }}</div>
    @if($from && $to)
        <div>Period: {{ $from }} to {{ $to }}</div>
    @endif
@endsection
