@extends('pdf.layout')

@section('title', 'Overall Beneficiaries Report')

@section('header_id')
    Invoice ID: {{ $invoice->invoice_number }}
@endsection

@section('content')
    <table class="products">
        <thead>
            <tr>
                <th>ID</th>
                <th>Date</th>
                <th>Beneficiary</th>
                <th>Program</th>
                <th>Amount</th>
                <th>Description</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($transactions as $transaction)
                <tr>
                    <td>{{ $transaction->id }}</td>
                    <td>{{ $transaction->transaction_date }}</td>
                    <td>{{ $transaction->beneficiary->full_name ?? 'N/A' }}</td>
                    <td>{{ $transaction->program->name ?? 'N/A' }}</td>
                    <td>{{ number_format($transaction->amount, 2) }}</td>
                    <td>{{ $transaction->description }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="6" style="text-align: center;">No transactions found.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="total">
        Total: {{ number_format($transactions->sum('amount'), 2) }}
    </div>
@endsection
@section('header_extra')
    <div>Report Date: {{ now()->format('Y-m-d') }}</div>
    <div>Generated by: {{ auth()->user()->name }}</div>
@endsection